yum/dnf customizable
Signed-off-by: Andrei Stepanov <astepano@redhat.com>

diff --git a/mtps-enable-mod-reqs b/mtps-enable-mod-reqs
--- a/mtps-enable-mod-reqs
+++ b/mtps-enable-mod-reqs
@@ -11,17 +11,16 @@
 #
 # See LICENSE for more details.
 #
-# Copyright: Red Hat Inc. 2019
+# Copyright: Red Hat Inc. 2019, 2023
 # Author: Andrei Stepanov <astepano@redhat.com>
 
 
 PROG="${PROG:-${0##*/}}"
 
-debug() {
-    if [ -n "$DEBUG" ]; then
-        echo "$*" >&2
-    fi
-}
+# Source `mtps-setup' from $PATH
+if command -v "mtps-setup" >/dev/null; then source "mtps-setup"; fi
+# If previous fails source `mtps-setup` from this script dir
+if [ -z "${YUMDNFCMD:-}" ]; then source "$(dirname "${BASH_SOURCE[0]}")/mtps-setup" || ( echo "Cannot source mtps-setup" >&2; exit 91 ); fi
 
 msg_usage() {
     cat << EOF
@@ -85,6 +84,7 @@ MMD="${MMD:-}"
 LOGS_DIR="${LOGS_DIR:-mtps-logs}"
 
 debug "MMD: $MMD"
+debug "Use ${YUMDNFCMD}"
 
 # Test correct invocation
 if [ -z "$MMD" ]; then
@@ -129,11 +129,11 @@ for require in "${requires[@]}"; do
             "  Stream:      $stream"
         logfname="${LOGS_DIR%%/}/$TESTRUN_ID-enable-$name-$stream.log"
         echo "Reset module: $name" | tee -a "$logfname"
-        yum -y module reset "$name" 2>&1 | tee -a "$logfname"
+        "${YUMDNFCMD}" -y module reset "$name" 2>&1 | tee -a "$logfname"
         test_status="${PIPESTATUS[0]}"
         if [ "$test_status" -eq "0" ]; then
             echo "Enable module: ${name}:${stream}" | tee -a "$logfname"
-            yum -y module enable "${name}:${stream}" 2>&1 | tee -a "$logfname"
+            "${YUMDNFCMD}" -y module enable "${name}:${stream}" 2>&1 | tee -a "$logfname"
             test_status="${PIPESTATUS[0]}"
         fi
         if [ "$test_status" -ne "0" ]; then
diff --git a/mtps-get-task b/mtps-get-task
--- a/mtps-get-task
+++ b/mtps-get-task
@@ -13,16 +13,15 @@ shopt -s extglob
 #
 # See LICENSE for more details.
 #
-# Copyright: Red Hat Inc. 2018
+# Copyright: Red Hat Inc. 2018, 2023
 # Author: Andrei Stepanov <astepano@redhat.com>
 
-RET_NO_PKG=7
+# Source `mtps-setup' from $PATH
+if command -v "mtps-setup" >/dev/null; then source "mtps-setup"; fi
+# If previous fails source `mtps-setup` from this script dir
+if [ -z "${YUMDNFCMD:-}" ]; then source "$(dirname "${BASH_SOURCE[0]}")/mtps-setup" || ( echo "Cannot source mtps-setup" >&2; exit 91 ); fi
 
-debug() {
-    if [ -n "$DEBUG" ]; then
-        echo "$*" >&2
-    fi
-}
+RET_NO_PKG=7
 
 rpms_from_answer() {
     local arch="$1" && shift
@@ -445,7 +444,7 @@ filter_available() {
     for rpm in $rpms; do
         rpm_file="$(basename "$rpm")"
         name="$(from_rpm_name "${rpm_file}" "name")"
-        yum info "${name}.${arch}" >/dev/null 2>&1
+        "$YUMDNFCMD" info "${name}.${arch}" >/dev/null 2>&1
         ret="$?"
         if [ "$ret" -ne 0 ]; then
             echo "Skipping as it is absent in shipped repos: $name" >&2
diff --git a/mtps-module-test b/mtps-module-test
--- a/mtps-module-test
+++ b/mtps-module-test
@@ -11,17 +11,16 @@
 #
 # See LICENSE for more details.
 #
-# Copyright: Red Hat Inc. 2019
+# Copyright: Red Hat Inc. 2019, 2023
 # Author: Andrei Stepanov <astepano@redhat.com>
 
 
 PROG="${PROG:-${0##*/}}"
 
-debug() {
-    if [ -n "$DEBUG" ]; then
-        echo "$*" >&2
-    fi
-}
+# Source `mtps-setup' from $PATH
+if command -v "mtps-setup" >/dev/null; then source "mtps-setup"; fi
+# If previous fails source `mtps-setup` from this script dir
+if [ -z "${YUMDNFCMD:-}" ]; then source "$(dirname "${BASH_SOURCE[0]}")/mtps-setup" || ( echo "Cannot source mtps-setup" >&2; exit 91 ); fi
 
 box_out() {
     local s=("$@")
@@ -119,24 +118,24 @@ fi
 p_remove() {
     local nsvc="$1" && shift
     local profile="$1" && shift
-    if ! dnf module info "$nsvc" 2>/dev/null | grep -q -E "^Profiles[[:space:]]*:.*${profile}[^,]*\[i\]"; then
+    if ! "$YUMDNFCMD" module info "$nsvc" 2>/dev/null | grep -q -E "^Profiles[[:space:]]*:.*${profile}[^,]*\[i\]"; then
         echo "Profile is not installed."
         return
     fi
-    yum -y module remove "$nsvc"
+    "$YUMDNFCMD" -y module remove "$nsvc"
 }
 
 p_install() {
     local nsvc="$1" && shift
     local profile="$1" && shift
     local name="${nsvc%%:*}"
-    if dnf module info "$nsvc" 2>/dev/null | grep -q -E "^Profiles[[:space:]]*:.*${profile}[^,]*\[i\]"; then
+    if "$YUMDNFCMD" module info "$nsvc" 2>/dev/null | grep -q -E "^Profiles[[:space:]]*:.*${profile}[^,]*\[i\]"; then
         echo "Profile is already installed."
         return
     fi
-    yum -y module reset "$nsvc"
-    yum -y module enable "$nsvc"
-    yum -y module install "$nsvc/$profile"
+    "$YUMDNFCMD" -y module reset "$nsvc"
+    "$YUMDNFCMD" -y module enable "$nsvc"
+    "$YUMDNFCMD" -y module install "$nsvc/$profile"
 }
 
 case $TEST in
diff --git a/mtps-run-tests b/mtps-run-tests
--- a/mtps-run-tests
+++ b/mtps-run-tests
@@ -11,17 +11,15 @@
 #
 # See LICENSE for more details.
 #
-# Copyright: Red Hat Inc. 2018, 2022
+# Copyright: Red Hat Inc. 2018, 2022, 2023
 # Author: Andrei Stepanov <astepano@redhat.com>
-
 
 PROG="${PROG:-${0##*/}}"
 
-debug() {
-    if [ -n "$DEBUG" ]; then
-        echo "$*" >&2
-    fi
-}
+# Source `mtps-setup' from $PATH
+if command -v "mtps-setup" >/dev/null; then source "mtps-setup"; fi
+# If previous fails source `mtps-setup` from this script dir
+if [ -z "${YUMDNFCMD:-}" ]; then source "$(dirname "${BASH_SOURCE[0]}")/mtps-setup" || ( echo "Cannot source mtps-setup" >&2; exit 91 ); fi
 
 # NEVRA - is a new package to test.
 msg_usage() {
@@ -34,7 +32,7 @@ Options:
 -s, --selinux=<0|1>                          one of: 0|1, defult: run tests in current selinux mode
 -l, --skiplangpack                           Do not test https://fedoraproject.org/wiki/Packaging:Langpacks
 -x, --scriptletcheck                         check output and fail if problems with scriptlets are found
--r, --repo=NAME                              YUM repo name, must be present, check with: yum repolist --enabled
+-r, --repo=NAME                              ${YUMDNFCMD} repo name, must be present, check with: ${YUMDNFCMD} repolist --enabled
 -c, --critical                               tests set are critical, example: update, downgrade
 -f, --rpmverify                              run "rpm --verify" to verify that what's installed matches the metadata in the RPM database
 -h, --help                                   display this help and exit
@@ -148,7 +146,7 @@ fi
 
 # https://bugzilla.redhat.com/show_bug.cgi?id=584525
 nevras_in_repo="$(
-    yum repoquery \
+    "$YUMDNFCMD" repoquery \
         --qf "%{repoid} %{name}-%{epoch}:%{version}-%{release}.%{arch}" 2>&1 | \
         sed -n -e "/^${REPONAME}[[:space:]]/ s/^${REPONAME}[[:space:]]//p"
 )"
@@ -173,8 +171,8 @@ TESTRUN_ID="$(date +%H%M%S)"
 if [ -z "${nevras_in_repo// /}" ]; then
     logfname="${LOGS_DIR%%/}/FAIL-$TESTRUN_ID-$TEST.log"
     echo "Test '$TEST' failed due no packages for testing in repo '$REPONAME:'." | tee -a "$logfname"
-    echo "Output for: yum repo-pkgs "$REPONAME" list --showduplicates" | tee -a "$logfname"
-    yum repo-pkgs "$REPONAME" list --showduplicates 2>&1 | tee -a "$logfname"
+    echo "Output for: ${YUMDNFCMD} repo-pkgs "$REPONAME" list --showduplicates" | tee -a "$logfname"
+    "$YUMDNFCMD" repo-pkgs "$REPONAME" list --showduplicates 2>&1 | tee -a "$logfname"
     exit 1
 fi
 
@@ -189,7 +187,7 @@ for nevra in $nevras_in_repo; do
     fi
     START_TIME="$NEW_START_TIME"
     # Save current YUM transaction ID, to revert it later
-    START="$(yum history list | sed -n -e '0,/^-\+$/d;s/^[[:space:]]*//p' | tr -s ' ' | cut -f 1 -d ' ' | sed -n -e '1p')"
+    START="$("$YUMDNFCMD" history list | sed -n -e '0,/^-\+$/d;s/^[[:space:]]*//p' | tr -s ' ' | cut -f 1 -d ' ' | sed -n -e '1p')"
     box_out \
         "TEST" \
         "====" \
@@ -197,7 +195,7 @@ for nevra in $nevras_in_repo; do
         "  TYPE:        $TEST" \
         "  NEVRA:       $nevra" \
         "  SELINUX:     $(getenforce || echo "unknown")" \
-        "  YUM HISTORY: $START"
+        "  ${YUMDNFCMD} HISTORY: $START"
     logfname="${LOGS_DIR%%/}/$TESTRUN_ID-$TEST-$nevra.log"
     mtps-pkg-test --test="$TEST" ${CHECK_SCRIPTLETS:+--scriptletcheck} ${RPM_VERIFY:+--rpmverify} --nevra="$nevra" 2>&1 | tee "$logfname"
     test_status="${PIPESTATUS[0]}"
diff --git a/profiles/fedora/prepare-system b/profiles/fedora/prepare-system
--- a/profiles/fedora/prepare-system
+++ b/profiles/fedora/prepare-system
@@ -13,17 +13,26 @@
 #
 # Copyright: Red Hat Inc. 2023
 # Author: Michal Srb <michal@redhat.com>
+# Andrei Stepanov <astepano@redhat.com>
 
 # Prepare system for install, remove, downgrade, update tests
 
+set -x
+
+# Source mtps-setup from $PATH
+if command -v "mtps-setup" >/dev/null; then source "mtps-setup"; fi
+# If previous fails source `mtps-setup` from this script dir
+# shellcheck disable=SC1091
+if [ -z "${YUMDNFCMD:-}" ]; then source "$(dirname "${BASH_SOURCE[0]}")/../../mtps-setup" || ( echo "Cannot source mtps-setup" >&2; exit 91 ); fi
+
 echo "Preparing the system for testing..."
 
-if [ -n "$FIXREPO" ]; then
+if [ -n "${FIXREPO:-}" ]; then
     echo "Ignoring \"--fixrepo\" option as it has no effect on Fedora profiles"
 fi
 
 # Add buildroot repo, if needed
-if [ -n "$ENABLE_BUILD_ROOT" ]; then
+if [ -n "${ENABLE_BUILD_ROOT:-}" ]; then
     echo "Enabling buildroot repository..."
     FEDORA_NUMBER=$(echo "${PROFILE}" | awk -F'-' '{ print $2 }')
 
@@ -38,16 +47,16 @@ EOF
 fi
 
 # Make sure fedora and fedora-updates repos are enabled
-dnf config-manager --set-enabled 'fedora' 'updates'
+"$YUMDNFCMD" config-manager --set-enabled 'fedora' 'updates'
 # Disable all COPR repositories (mini-tps, ...)
-dnf config-manager --set-disabled 'copr:*'
+"$YUMDNFCMD" config-manager --set-disabled 'copr:*'
 
 echo "Recreating the DNF cache..."
-dnf clean all
-dnf makecache
+"$YUMDNFCMD" clean all
+"$YUMDNFCMD" makecache
 
 echo "Installing packages required for testing..."
-dnf install -y createrepo_c
+"$YUMDNFCMD" install -y createrepo_c
 
 echo "Updating the system..."
-dnf update -y
+"$YUMDNFCMD" update -y
